# Stærðfræði og reiknifræði – Fyrirlestraræfing 11

In [1]:
#BYRJA -- Keyrið til að frumstilla numpy o.fl.
import numpy as np
import numpy.random as npr
import numpy.linalg as la
import matplotlib.pyplot as plt
plt.rc('axes', axisbelow=True)
%matplotlib inline
# disp(x,y...) skrifar x,y... með 3 aukastöfum
def disp(*args): print(*(f'{a:.3f}' if isinstance(a,float) else a for a in args))
np.set_printoptions(precision=3, floatmode='fixed', suppress=True)

def ör(x,y,dx,dy):
    """Teiknar ör með örvaroddi frá (x,y) til (x+dx, y+dy)"""
    plt.annotate('', (x+dx,y+dy), (x,y), arrowprops = {'width':0.5, 'headwidth':6, 'fc':'k'})

1. Búið til eitthvað samhverft 2 sinnum 2 fylki $A$ og sannreynið með Numpy að $A^T = A$

In [6]:
#1
A = np.array([[5,6],[7,8]])
print( A.T )

[[5 7]
 [6 8]]


2. Lát
   $$A = \pmatrix{1 & 2\\3 & 4}\text{ og }x = \pmatrix{2\\3}$$
   og sannreynið bæði með blaði og blýanti og með Numpy að $Ax$ er línuleg samantekt af dálkum    fylkisins með samantektarstuðlum sem eru stök $x$ (sem sé $2$ og $3$).

In [14]:
#2
A = np.array([[1,2],[3,4]])
x = np.array([2,3])
print(A@x)
print(A*x)
print('Kristján, þú verður að vanda þig betur þegar þú skrifar.')
print('Þetta dæmi t.d. er hrikalega illa skrifað.')
print('Ég skil ekki orð sem þú segir. Þú skrifar eins og afturgenginn halanegri.')

[ 8 18]
[[ 2  6]
 [ 6 12]]
Kristján, þú verður að vanda þig betur þegar þú skrifar.
Þetta dæmi t.d. er hrikalega illa skrifað.
Ég skil ekki orð sem þú segir. Þú skrifar eins og afturgenginn halanegri.


3. Lát $A$ vera eins og í dæmi 2 og reiknið með Numpy $3*A$, $A + A$ og $A + A^T$ og $\|A\|$ (`la.norm` reiknar það síðastnefnda). Reiknið líka normið með blaði og blýanti.

In [25]:
#3
print(3*A)
print(A+A)
print(A+A.T)
disp(np.sqrt(1**2+2**2+3**2+4**2))
disp(la.norm(A))

[[ 3  6]
 [ 9 12]]
[[2 4]
 [6 8]]
[[2 5]
 [5 8]]
5.477
5.477


4. Búið til 5 sinnum 5 fylki fyrir uppsafnaða summu (*running sum*) og beitið því á vigurinn $x = (2, 3, 4, 5, 6)$.

In [23]:
#4
F = np.random.random((5,5))
disp(F)

[[0.689 0.936 0.759 0.167 0.748]
 [0.620 0.961 0.115 0.466 0.956]
 [0.828 0.586 0.904 0.461 0.555]
 [0.293 0.959 0.821 0.800 0.416]
 [0.738 0.059 0.646 0.652 0.113]]


5. Látið $p = 2 - x + 3x^2$ og notið fylkjamargföldun með viðeigandi fylki $A$ til að reikna gildi $p$ í punktunum $t_i = 1$, $2$ og $3$.

In [31]:
#5
A = np.zeros((3,3))
c = np.array([2,-1,3])
t = np.array([1,2,3])
for i in range(3):
    for j in range(3):
        A[i,j] = t[i]**j
        
disp(A)
disp(A@c)

[[1.000 1.000 1.000]
 [1.000 2.000 4.000]
 [1.000 3.000 9.000]]
[ 4.000 12.000 26.000]


6. Búið snúningsfylki $A$ fyrir snúning um 60° rangsælis Teiknið vigurinn $a = (2,1)$ og reiknið og teiknið $b$ = snúning hans með $A$.

In [7]:
#6

7. Látið $B$ spegla um línuna $y = x$, látið $a$ vera eins og í dæmi 1 og $c$ vera speglaða vigurinn. Reiknið og teiknið.

In [8]:
#7

8. Búið til fylki fyrir netið á mynd 7.3 á bls. 134. Látið flæðið vera $x_j = j$ fyrir öll $j$ og reiknið inn/útstreymin $s_i, i = 1\ldots 4$.

In [9]:
#8