# Kynning á *NumPy:* Python fyrir fylkjareikninga

In [12]:
# R1  vigrar og fylki
import numpy as np
v = np.array([0., 2.])
A = np.array([[2., 3.], [4., 5.]])
# aefing 2
B = np.array([[2,3],[4,5]])
# aefing 3
x = np.array([3,4,5,6])
print('v =', v)
print('A ='); print(A)
print(f'ndim={A.ndim}, shape={A.shape}, size={A.size}, dtype={A.dtype}')
# aefing 1
print('XXA =', A)
print(f'YA =\n{A}')
# aefing 2
print(B.dtype)

v = [0. 2.]
A =
[[2. 3.]
 [4. 5.]]
ndim=2, shape=(2, 2), size=4, dtype=float64
XXA = [[2. 3.]
 [4. 5.]]
YA =
[[2. 3.]
 [4. 5.]]
int64


**Ath.** Í stærðfræði væri vigurinn táknaður $(0, 2)$ eða $\pmatrix{0 \\ 2}$ og fylkið væri táknað $\pmatrix{2 & 3 \\ 4 & 5}$. Stundum eru notaðir hornklofar [...] í stað sviga.

***Æfing:***
1. Prófið `print('A =', A)` og líka `print(f'A =\n{A}')`
2. Prófið að sleppa tugtölupunktunum: `B = np.array([2, 3], [4, 5]` og print(B.dtype)
3. Búið til vigur x = (3,4,5,6)

In [3]:
import numpy as np
# R2  Föll til að búa til fylki
Z = np.zeros((2,2))
B = np.eye(2)
e = np.ones((1,4))  # Hefð að nota litla stafi til að tákna vigra og stóra til að tákna fylki
F = np.full((3,5), 3.14159)
k = np.arange(1,11)
h = np.linspace(0,5,11)
print("Z")
print(Z) 
print("B")
print(B)
print(f'e = {e}'); print(F)
print(f'k = {k}, dtype={k.dtype}')
print(f'h = {h}, dtype={h.dtype}')

Z
[[0. 0.]
 [0. 0.]]
B
[[1. 0.]
 [0. 1.]]
e = [[1. 1. 1. 1.]]
[[3.14159 3.14159 3.14159 3.14159 3.14159]
 [3.14159 3.14159 3.14159 3.14159 3.14159]
 [3.14159 3.14159 3.14159 3.14159 3.14159]]
k = [ 1  2  3  4  5  6  7  8  9 10], dtype=int64
h = [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ], dtype=float64


***Æfing:***
1. Stikinn verður að vera par: Prófið að kalla á `npr.zeros(2,2)`
2. Prófið að breyta víddum fylkjanna. 
3. Prófið að skoða dtype af fleiri fylkjum.

In [114]:
# R3  Hægt er að stilla fjölda aukastafa o.fl. í útskrift:
np.set_printoptions(precision=3, floatmode = 'fixed', suppress=True)
A = np.full((3,5), 3.14159)
print('A = '); print(A)

# Stillt aftur á sjálfgefna útskrift:
# np.set_printoptions(precision=8, suppress=False) # reset to default

A = 
[[3.142 3.142 3.142 3.142 3.142]
 [3.142 3.142 3.142 3.142 3.142]
 [3.142 3.142 3.142 3.142 3.142]]


***Æfing:***
Keyrið reit R3 og svo reit R2 aftur

In [120]:
# R4  Slembifylki
import numpy.random as npr
for i in range(5):
    A = npr.random((2,2))  # tekur inn par, gefur 2 x 2 slembifylki
    print(A)

[[0.771 0.676]
 [0.168 0.944]]
[[0.453 0.107]
 [0.837 0.543]]
[[0.552 0.432]
 [0.889 0.325]]
[[0.692 0.576]
 [0.988 0.670]]
[[0.356 0.280]
 [0.965 0.295]]


***Æfing:***
Keyrið reit R4 aftur og aftur

In [8]:
# R5  Fylkja og vigurreikningar
A = np.array([[2., 3.], [4., 5.]])
x = np.array([1, 2, 3], dtype=float)
y = np.array([1.0, 1.0, 2.0])
z = x + y       # tilsvarandi stök lögð saman
B = A*A         # -- og margfölduð
S = np.sqrt(A)  # tekur kvaðratrót af hverju staki
E = np.exp(A)   # og exp (líka til np.sin, np.log o.s.frv.)
print(z); print(B)
print(S); print(E)

[2. 3. 5.]
[[ 4.  9.]
 [16. 25.]]
[[1.41421356 1.73205081]
 [2.         2.23606798]]
[[  7.3890561   20.08553692]
 [ 54.59815003 148.4131591 ]]


***Æfing:***
Prófið fleiri aðgerðir (mínus, deilingu, margföldun fylkis og tölu)