# Tímadæmi 13 – Fylki fyrir net

In [2]:
#BYRJA -- Keyrið til að frumstilla
import numpy as np
from scipy.sparse.csgraph import dijkstra 
# disp(x,y...) skrifar x,y... með 3 aukastöfum
def disp(*args): print(*(f'{a:.3f}' if isinstance(a,float) else a for a in args))
np.set_printoptions(precision=4, floatmode='fixed', suppress=True, linewidth=150)

## A  Legufylki og flæði
Í þessu dæmi lítum við aftur á netið í dæmi S10B, og í þetta sinn notum við Python til reikna inn- og útstreymi. Upplýsingarnar um það eru í skrá `s10b.txt` á Piazza. Dálkarnir `b` og `e` gefa byrjunar- og endahnút hverrar örvar (eða leggs), `x` gefur flæði eftir henni og `lengd` gefur lengd hennar. Hér eru nokkrar skipanir sem nota þarf (flestar eru upprifjun):


    np.loadtxt("skrá.txt", int, skiprows=n)   Skilar int-fylki (sjálfgefið float)
    (d1,d2,d3) = np.loadtxt(...).T            Skilar skrá með 3 dálkum í 3 vigrum
    max(a,b)                                  Sú stærri af tölunum a og b
    x.max()                                   Stærsta stak í numpy-vigri x
    len(x)                                    Lengd vigurs x
    np.zeros((m,n), int)                      m x n heiltölu-núllfylki
    A @ x                                     Fylki sinnum vigur
    disp(x)                                   Skrifar út x með fallinu að ofan
    D = dijkstra(L)                           Skilar D[i,j] = lengd stysta vegar
                                              frá hnút i til hnúts j ef L[i,j] er
                                              lengd örvarinnar i➞j
    
1. Lesið skrána `s10b.txt` inn í fimm vigra, `ör`, `b`, `e`, `x` og `lengd` og sannfærið ykkur um að það hafi tekist.


2. Ákvarðið `m` = fjölda hnúta og `n` = fjölda örva með `max` og `len`


3. Legufylki nets með $m$ hnúta og $n$ örvar er $m \times n$ og hefur $-1$ og $1$ í sætum $(i_1, j)$ og $(i_2,j)$ ef ör nr. $j$ byrjar í hnút $i_1$ og endar í hnút $i_2$. Búið til legufylki $A$ með því að lykkja yfir allar örvarnar (með $k$) og setja $-1$ og $1$ inn í fylkið á rétta staði (ath. að taka með í reikninginn að Python byrjar að tölusetja í 0, látið t.d. `i1 = b[k]-1`). Skrifið fylkið út. 


4. Finnið lindir og ósa og hve mikið flæðir inn og út með því að nota varðveislujöfnuna $Ax + s = 0$ þar sem $s$ er inn-/útflæðið.

In [36]:
# 1)
(ero, b, e, x, lengd) = np.loadtxt('s10b.txt', int, skiprows=1).T
# 2)
m = max(b.max(), e.max())
print('foldi hnuta:', m)
n = len(ero)
print('fjoldi orva:', n)
# 3)
A = np.zeros((m, n), int)

for i in range(len(ero)):
    j = ero[i]-1
    i1 = b[i]-1
    i2 = e[i]-1
    A[i1, j] = -1
    A[i2, j] = 1

print(A)
# 4)
s = -A @ x
print(s)

foldi hnuta: 6
fjoldi orva: 9
[[-1  0  0  0  0  0  0  0 -1]
 [ 1 -1  0  0  0  0 -1  0  0]
 [ 0  1 -1  0  0  0  0 -1  1]
 [ 0  0  1 -1  0 -1  1  0  0]
 [ 0  0  0  1 -1  0  0  1  0]
 [ 0  0  0  0  1  1  0  0  0]]
[ 10   8   0   0  -7 -11]


## B  Grannafylki og fjarlægðir
1. Grannafylki nets með $n$ hnúta er $n\times n$ fylki $G$ með  $G_{ij} = 1$ ef hnútur $i$ er tengdur hnút $j$ með ör (hér fylgjum við skilgreiningu Stærðfræðimynstra, en Standford-bókin er með þetta bylt). Búið til $G$ fyrir netið í dæmi A með því að lykkja yfir örvarnar með $k$, finna byrjunar- og endahnút hverrar örvar og setja $1$ á réttan stað í fylkinu (**Leiðbeining:** *`i = b[k] - 1` og `j = e[k] - 1`*). Skrifið fylkið út.


2. Hægt er að nota reiknirit sem kennt er við Dijkstra til að finna stystu fjarlægð milli tveggja hnúta í neti. Ef við sendum grannafylki inn í Dijkstra er fjarlæðin reiknuð með því að telja örvarnar veginum. Notið SciPy-útgáfuna af Dijkstra til að finna lágmarksfjölda  örva í vegi frá 1 til 6.


3. Hægt er að búa til lengdafylki $L$ með eins lykkju og notuð var til að finna grannafylkið, nema við setjum $L_{ij}$ = lengd örvarinnar $i\to j$. Gerið það, og finnið í framhaldi lengd stysta vegar frá 1 til 6.

In [49]:
# 1)
G = np.zeros((m, m), int)
for k in range(len(ero)):
    i = b[k] - 1
    j = e[k] - 1
    G[i,j] = 1
    
print(G)
# 2)
print( dijkstra(G) )

[[0 1 1 0 0 0]
 [0 0 1 1 0 0]
 [0 0 0 1 1 0]
 [0 0 0 0 1 1]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]]
[[0.0000 1.0000 1.0000 2.0000 2.0000 3.0000]
 [   inf 0.0000 1.0000 1.0000 2.0000 2.0000]
 [   inf    inf 0.0000 1.0000 1.0000 2.0000]
 [   inf    inf    inf 0.0000 1.0000 1.0000]
 [   inf    inf    inf    inf 0.0000 1.0000]
 [   inf    inf    inf    inf    inf 0.0000]]
